/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/common/ActionButton.vue')['default']
    CheckUpdateButton: typeof import('./src/components/update/CheckUpdateButton.vue')['default']
    DownloadProgress: typeof import('./src/components/common/DownloadProgress.vue')['default']
    GameCard: typeof import('./src/components/common/GameCard.vue')['default']
    LogViewer: typeof import('./src/components/common/LogViewer.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateDisplay: typeof import('./src/components/common/StateDisplay.vue')['default']
    StatusCard: typeof import('./src/components/common/StatusCard.vue')['default']
    TrainerCard: typeof import('./src/components/common/TrainerCard.vue')['default']
    TrainerListItem: typeof import('./src/components/common/TrainerListItem.vue')['default']
    TrainerSkeleton: typeof import('./src/components/common/TrainerSkeleton.vue')['default']
    UpdateDialog: typeof import('./src/components/update/UpdateDialog.vue')['default']
    VirtualGrid: typeof import('./src/components/common/VirtualGrid.vue')['default']
    WindowLayout: typeof import('./src/components/layouts/WindowLayout.vue')['default']
  }
}
