// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main service exposed to the Wails frontend.
 * All methods on this struct are callable from JavaScript via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload aborts an in-flight download for the given trainer id.
 * Returns an error if no download is currently running for that trainer.
 */
export function CancelDownload(trainerID: number): $CancellablePromise<void> {
    return $Call.ByID(2568664968, trainerID);
}

/**
 * CancelRefresh asks an in-progress crawl to stop after the current page.
 * Returns an error if no crawl is running. The summary emitted to the UI on
 * completion is annotated with "(已取消)" so the user knows it was not a
 * normal finish.
 */
export function CancelRefresh(): $CancellablePromise<void> {
    return $Call.ByID(1684824803);
}

/**
 * DeleteTrainer removes a downloaded/installed trainer.
 */
export function DeleteTrainer(trainerID: number): $CancellablePromise<void> {
    return $Call.ByID(73366834, trainerID);
}

/**
 * DownloadTrainer downloads a trainer file.
 * Runs synchronously; progress is emitted via the "download:progress" event.
 * Use CancelDownload(trainerID) to abort an in-flight download.
 */
export function DownloadTrainer(trainerID: number): $CancellablePromise<void> {
    return $Call.ByID(1680021711, trainerID);
}

/**
 * GetDataDir returns the data directory path.
 */
export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(655531069);
}

/**
 * GetDownloadedTrainers returns all trainers with status = downloaded or installed.
 */
export function GetDownloadedTrainers(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3522053005).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetInstalledTrainers returns all trainers with status = installed.
 */
export function GetInstalledTrainers(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(1357693582).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMappingCount returns the number of loaded name-mapping entries.
 */
export function GetMappingCount(): $CancellablePromise<number> {
    return $Call.ByID(1087103351);
}

/**
 * GetMappingEntries returns a paginated, optionally filtered, view of the
 * name-mapping table. Used by the mapping-management UI in Settings.
 * query is a case-insensitive substring match against name_en, name_zh,
 * and aliases. offset/limit control pagination.
 */
export function GetMappingEntries(query: string, offset: number, limit: number): $CancellablePromise<$models.MappingEntry[]> {
    return $Call.ByID(3537339080, query, offset, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRefreshResult returns the human-readable result of the last refresh.
 */
export function GetRefreshResult(): $CancellablePromise<string> {
    return $Call.ByID(1422973628);
}

/**
 * GetSettings returns app settings from kv_store.
 */
export function GetSettings(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3018893939).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTotalGames returns the total number of games in the index.
 */
export function GetTotalGames(): $CancellablePromise<number> {
    return $Call.ByID(1282712555);
}

/**
 * GetTrainerDetail returns detail for a specific game (all trainer versions).
 * 
 * If trainer details are already cached, this is fast and synchronous.
 * If they are NOT cached (typical for games found through remote search),
 * this returns a sentinel error so the frontend can show a loading state
 * and call PrefetchTrainerDetail(gameID) to fetch in the background; that
 * call emits a "detail:progress" event when done, after which the frontend
 * calls GetTrainerDetail again to render the data.
 * 
 * This avoids blocking the (single-threaded) Wails binding call on a slow
 * remote fetch, which previously froze the whole UI for several seconds.
 */
export function GetTrainerDetail(gameID: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2168190618, gameID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTrainers returns paginated trainers for the home page.
 * Returns games sorted by update time with their trainer info and states.
 */
export function GetTrainers(page: number, pageSize: number): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3275446408, page, pageSize).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * InstallTrainer installs a downloaded trainer.
 */
export function InstallTrainer(trainerID: number): $CancellablePromise<void> {
    return $Call.ByID(2170736966, trainerID);
}

/**
 * IsRefreshing reports whether a refresh task is currently running.
 */
export function IsRefreshing(): $CancellablePromise<boolean> {
    return $Call.ByID(129364187);
}

/**
 * LaunchTrainer launches an installed trainer executable.
 */
export function LaunchTrainer(trainerID: number): $CancellablePromise<void> {
    return $Call.ByID(3314639258, trainerID);
}

/**
 * PrefetchTrainerDetail explicitly kicks off a background fetch of a game's
 * detail page and returns immediately. Completion is reported via the
 * "detail:progress" event with {game_id, done, error}. Safe to call even if
 * a fetch is already running for the same game (no-op in that case).
 */
export function PrefetchTrainerDetail(gameID: number): $CancellablePromise<void> {
    return $Call.ByID(3403783371, gameID);
}

/**
 * RefreshData fetches latest data from flingtrainer.com asynchronously.
 * It returns immediately; progress and completion are reported via the
 * "refresh:progress" event. Use IsRefreshing() / GetRefreshResult() to poll.
 * 
 * If a previous crawl was interrupted, this resumes from the last page that
 * was successfully saved (so closing and reopening the app doesn't restart
 * the full crawl from page 1). Once finished, the resume marker is cleared.
 */
export function RefreshData(): $CancellablePromise<void> {
    return $Call.ByID(983148913);
}

/**
 * RefreshDataSync fetches latest data synchronously and returns when done.
 * Useful for first-run seeding or tests; prefer RefreshData from the UI.
 * Fetches ALL pages (full library) so search works for every FLiNG game.
 */
export function RefreshDataSync(): $CancellablePromise<string> {
    return $Call.ByID(2242894894);
}

/**
 * SaveSettings saves settings to kv_store.
 */
export function SaveSettings(settings: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(3784651466, settings);
}

/**
 * SearchRemoteExplicit performs a LIVE search against flingtrainer.com.
 * 
 * This is the escape hatch used when the local library doesn't have what
 * the user wants (the dropdown's "🔍 联网搜索更多..." item). It resolves a
 * Chinese query to English titles via the name mapping, queries the site,
 * caches the results locally, and rebuilds the in-memory index so subsequent
 * detail lookups resolve.
 * 
 * Because it's user-initiated (not on every keystroke), the multi-second
 * latency is acceptable.
 */
export function SearchRemoteExplicit(query: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(2707682292, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SearchSuggestions returns up to `limit` lightweight autocomplete candidates
 * ranked by match quality (exact > prefix > substring). Used by the search
 * box dropdown so the user sees candidates as they type. Pure in-memory;
 * never hits the network or the DB.
 * 
 * Each item carries only the fields the dropdown needs (id, names, cover,
 * options) — no trainer/state construction — so a 10-item call is cheap.
 */
export function SearchSuggestions(query: string, limit: number): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(2725045639, query, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SearchTrainers performs a LOCAL-first search.
 * 
 * The local DB now holds the full library (~731 games after a full crawl),
 * so the common case is an instant in-memory lookup that hits no network
 * and writes nothing. Only when the user explicitly wants to look beyond
 * the local library do we hit the remote site — via SearchRemoteExplicit.
 * 
 * If the local index returns zero matches the result is simply empty; the
 * frontend renders a "🔍 联网搜索更多..." affordance that calls
 * SearchRemoteExplicit on click. This keeps typing responsive: every
 * keystroke resolves in < 5ms instead of firing 5 HTTP requests + a DB
 * upsert + a full index rebuild.
 */
export function SearchTrainers(query: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(903045308, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetDownloadDir configures the download directory and creates it if needed.
 */
export function SetDownloadDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1936248769, dir);
}

/**
 * SetWindow stores a reference to the main window so the service can emit events.
 * Called from main() after the window is created.
 */
export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3141033926, w);
}

/**
 * Shutdown closes the database connection on app exit.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(780008012);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MappingEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
