// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main service exposed to the Wails frontend.
 * All methods on this struct are callable from JavaScript via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * DeleteTrainer removes a downloaded/installed trainer.
 * @param {number} trainerID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTrainer(trainerID) {
    return $Call.ByID(73366834, trainerID);
}

/**
 * DownloadTrainer downloads a trainer file.
 * Runs synchronously; progress is emitted via the "download:progress" event.
 * @param {number} trainerID
 * @returns {$CancellablePromise<void>}
 */
export function DownloadTrainer(trainerID) {
    return $Call.ByID(1680021711, trainerID);
}

/**
 * GetDataDir returns the data directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetDataDir() {
    return $Call.ByID(655531069);
}

/**
 * GetDownloadedTrainers returns all trainers with status = downloaded or installed.
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetDownloadedTrainers() {
    return $Call.ByID(3522053005).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetInstalledTrainers returns all trainers with status = installed.
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetInstalledTrainers() {
    return $Call.ByID(1357693582).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetMappingCount returns the number of loaded name-mapping entries.
 * @returns {$CancellablePromise<number>}
 */
export function GetMappingCount() {
    return $Call.ByID(1087103351);
}

/**
 * GetRefreshResult returns the human-readable result of the last refresh.
 * @returns {$CancellablePromise<string>}
 */
export function GetRefreshResult() {
    return $Call.ByID(1422973628);
}

/**
 * GetSettings returns app settings from kv_store.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSettings() {
    return $Call.ByID(3018893939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTotalGames returns the total number of games in the index.
 * @returns {$CancellablePromise<number>}
 */
export function GetTotalGames() {
    return $Call.ByID(1282712555);
}

/**
 * GetTrainerDetail returns detail for a specific game (all trainer versions).
 * @param {number} gameID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetTrainerDetail(gameID) {
    return $Call.ByID(2168190618, gameID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTrainers returns paginated trainers for the home page.
 * Returns games sorted by update time with their trainer info and states.
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetTrainers(page, pageSize) {
    return $Call.ByID(3275446408, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * InstallTrainer installs a downloaded trainer.
 * @param {number} trainerID
 * @returns {$CancellablePromise<void>}
 */
export function InstallTrainer(trainerID) {
    return $Call.ByID(2170736966, trainerID);
}

/**
 * IsRefreshing reports whether a refresh task is currently running.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRefreshing() {
    return $Call.ByID(129364187);
}

/**
 * LaunchTrainer launches an installed trainer executable.
 * @param {number} trainerID
 * @returns {$CancellablePromise<void>}
 */
export function LaunchTrainer(trainerID) {
    return $Call.ByID(3314639258, trainerID);
}

/**
 * RefreshData fetches latest data from flingtrainer.com asynchronously.
 * It returns immediately; progress and completion are reported via the
 * "refresh:progress" event. Use IsRefreshing() / GetRefreshResult() to poll.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshData() {
    return $Call.ByID(983148913);
}

/**
 * RefreshDataSync fetches latest data synchronously and returns when done.
 * Useful for first-run seeding or tests; prefer RefreshData from the UI.
 * @returns {$CancellablePromise<string>}
 */
export function RefreshDataSync() {
    return $Call.ByID(2242894894);
}

/**
 * SaveSettings saves settings to kv_store.
 * @param {{ [_ in string]?: any }} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3784651466, settings);
}

/**
 * SearchTrainers searches by query (Chinese or English).
 * @param {string} query
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function SearchTrainers(query) {
    return $Call.ByID(903045308, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetDownloadDir configures the download directory and creates it if needed.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetDownloadDir(dir) {
    return $Call.ByID(1936248769, dir);
}

/**
 * SetWindow stores a reference to the main window so the service can emit events.
 * Called from main() after the window is created.
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetWindow(w) {
    return $Call.ByID(3141033926, w);
}

/**
 * Shutdown closes the database connection on app exit.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(780008012);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
