// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MappingEntry mirrors service.MappingEntry for the frontend.
 */
export class MappingEntry {
    /**
     * Creates a new MappingEntry instance.
     * @param {Partial<MappingEntry>} [$$source = {}] - The source object to create the MappingEntry.
     */
    constructor($$source = {}) {
        if (!("name_en" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name_en"] = "";
        }
        if (!("name_zh" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name_zh"] = "";
        }
        if (!("aliases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["aliases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MappingEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MappingEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField2_0($$parsedSource["aliases"]);
        }
        return new MappingEntry(/** @type {Partial<MappingEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
