// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MappingEntry mirrors service.MappingEntry for the frontend.
 */
export class MappingEntry {
    "name_en": string;
    "name_zh": string;
    "aliases": string[];

    /** Creates a new MappingEntry instance. */
    constructor($$source: Partial<MappingEntry> = {}) {
        if (!("name_en" in $$source)) {
            this["name_en"] = "";
        }
        if (!("name_zh" in $$source)) {
            this["name_zh"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MappingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MappingEntry {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField2_0($$parsedSource["aliases"]);
        }
        return new MappingEntry($$parsedSource as Partial<MappingEntry>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
